name: Build
on:
  push:
    branches:
      - main # or the name of your main branch

jobs:
  sonarcloud:
    name: Build
    runs-on: self-hosted
    container:
      image: sonarsource/sonar-scanner-cli:latest
      volumes: 
       - ${{ github.workspace }}:/workspace
    steps:
      - name: run multi command
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          ls /workspace
          sonar-scanner -Dsonar.projectKey=github -Dsonar.sources=. -Dsonar.host.url=http://10.125.69.99:9000 -Dsonar.login=admin -Dsonar.password=AutoTune

