name: Build
on:
  push:
    branches:
      - main # or the name of your main branch

jobs:
  sonarcloud:
    name: Build
    runs-on: self-hosted
    container:
      image: sonarsource/sonar-scanner-cli:latest
      volumes: 
       - autotune_gitlabRunner_autotune:/home/autotune
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: run multi command
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          http_proxt: ${{ secrets.HTTP_PROXY }}
          HTTP_PROXY: ${{ secrets.HTTP_PROXY }}
          https_proxt: ${{ secrets.HTTPS_PROXY }}
          HTTPS_PROXY: ${{ secrets.HTTPS_PROXY }}
          NO_PROXY: ${{ secrets.NO_PROXY }}
        run: |
          /home/autotune/lib.linux-x86_64-3.8/math.py
          sh -x /home/autotune/SonarQube/before_scripts.sh
          sh -x /home/autotune/SonarQube/run_autotune.sh 
          sonar-scanner -Dsonar.projectKey=github -Dsonar.sources=. -Dsonar.host.url=http://10.125.69.99:9000 -Dsonar.login=admin -Dsonar.password=AutoTune
          sh -x /home/autotune/SonarQube/after_scripts.sh

