name: Build
on:
  push:
    branches:
      - main # or the name of your main branch

jobs:
  build:
    name: Build
    runs-on: self-hosted
    steps:
      - name: run multi command
        run: |  # <- ここがミソ
          git config --global user.email "city1@outlook.ccom"
          git config --global user.name "hirai247"
          git add .
          git commit -m 'modify manifests'
          git status

